### PR TITLE
Adding code version for Arduino Leonardo/Pro Micro

### PR DESCRIPTION
**Pull request by DRCRecoveryData**
Add board name of boards.txt from path:

```C:\Users\Administrator\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\boards.txt```

Original code:
```
  TinyUSBDevice.setID(0xFB83, 0x5000); // 0xFB83 is an unused USB manufacturer ID.
  usb_midi.setStringDescriptor("Ghost Note Audio Conductor");
  TinyUSBDevice.setManufacturerDescriptor("Ghost Note Audio");
  TinyUSBDevice.setProductDescriptor("Conductor");
  TinyUSBDevice.setSerialDescriptor("Ghost Note Conductor");
```

Add custom board name for Arduino Leonardo/Pro Micro by:

```
##############################################################

leonardo.name=Ghost Note Audio Conductor

# Original VID and PID entries
leonardo.vid.0=0x2341
leonardo.pid.0=0x0036
leonardo.vid.1=0x2341
leonardo.pid.1=0x8036
leonardo.vid.2=0x2A03
leonardo.pid.2=0x0036
leonardo.vid.3=0x2A03
leonardo.pid.3=0x8036
leonardo.vid.4=0x2341
leonardo.pid.4=0x8036

# Custom VID and PID entry
leonardo.vid.5=0xFB83
leonardo.pid.5=0x5000

# Upload port configurations
leonardo.upload_port.0.vid=0x2341
leonardo.upload_port.0.pid=0x0036
leonardo.upload_port.1.vid=0x2341
leonardo.upload_port.1.pid=0x8036
leonardo.upload_port.2.vid=0x2A03
leonardo.upload_port.2.pid=0x0036
leonardo.upload_port.3.vid=0x2A03
leonardo.upload_port.3.pid=0x8036
leonardo.upload_port.4.vid=0x2341
leonardo.upload_port.4.pid=0x8036

# Upload tool configurations
leonardo.upload.tool=avrdude
leonardo.upload.tool.default=avrdude
leonardo.upload.tool.network=arduino_ota

# Bootloader configurations
leonardo.bootloader.tool=avrdude
leonardo.bootloader.tool.default=avrdude
leonardo.bootloader.low_fuses=0xff
leonardo.bootloader.high_fuses=0xd8
leonardo.bootloader.extended_fuses=0xcb
leonardo.bootloader.file=caterina/Caterina-Leonardo.hex
leonardo.bootloader.unlock_bits=0x3F
leonardo.bootloader.lock_bits=0x2F

# Build configurations
leonardo.build.mcu=atmega32u4
leonardo.build.f_cpu=16000000L
leonardo.build.vid=0x2341
leonardo.build.pid=0x8036
leonardo.build.usb_product="Arduino Leonardo"
leonardo.build.board=AVR_LEONARDO
leonardo.build.core=arduino
leonardo.build.variant=leonardo
leonardo.build.extra_flags={build.usb_flags}

# USB Manufacturer and Product descriptors
leonardo.vid.5.name=Ghost Note Audio
leonardo.pid.5.name=Conductor

# Serial descriptor
leonardo.serial=Ghost Note Conductor

##############################################################
```

Screenshot (2)

Screenshot (3)

### CODE REVIEW

**Comment by GhostNoteAudio** [comment]
Hello. I very much appreciate the effort you've put in here. Unfortunately, I can't really merge this into our codebase due to the following reasons:

- The additional code is not useful for the production version of our controller. We won't have any ability, or need, to test and maintain the Leonardo and Uno versions, so it's likely that it will go stale and break relatively quickly.
- This gives us 5 files to maintain and keep in sync, vs. just one. That's a lot of extra work for no benefit to the project. That additional works needs time, and time costs money, and it's not a cost I'm willing to transfer over to my customers.
- The Arduino Uno is not capable of USB communication, beyond serial communications. It is not possible to run Uno as a Midi class-compliant device, so I can't see how that part of the code would ever work.

I think it is much better if you fork the repository and host a modified version for your own use. We will continue to make changes to the master repository (this repo), and you should be able to pull latest changes and apply them to your modified files as needed.

**Comment by DRCRecoveryData** [comment]
> Hello. I very much appreciate the effort you've put in here. Unfortunately, I can't really merge this into our codebase due to the following reasons:
> 
> 
> 
> - The additional code is not useful for the production version of our controller. We won't have any ability, or need, to test and maintain the Leonardo and Uno versions, so it's likely that it will go stale and break relatively quickly.
> 
> - This gives us 5 files to maintain and keep in sync, vs. just one. That's a lot of extra work for no benefit to the project. That additional works needs time, and time costs money, and it's not a cost I'm willing to transfer over to my customers.
> 
> - The Arduino Uno is not capable of USB communication, beyond serial communications. It is not possible to run Uno as a Midi class-compliant device, so I can't see how that part of the code would ever work.
> 
> 
> 
> I think it is much better if you fork the repository and host a modified version for your own use. We will continue to make changes to the master repository (this repo), and you should be able to pull latest changes and apply them to your modified files as needed.

Could you upload the top plate demesion file from it? also which is the fader model you used?

**Comment by GhostNoteAudio** [comment]
Our units use Alps faders. Unfortunately I'm not willing to share the top panel design as it is copyrighted artwork (it contains our trademarked logo and artwork). If you are 3D printing your own enclosure from the STL file we provided in the repository, then getting the dimensions from that should be straight forward. Otherwise, if you are working on building your own unit from scratch, I'd recommend designing a custom enclosure and panel.

**Comment by DRCRecoveryData** [comment]
Do you have the demension like dxf file position of fader holes?

**Pull request closed without merging**
